### ISSUE TITLE
Wrapping App (root) withPendoSDK yields Invariant Violation on AppRegistry

### ISSUE THREAD

**Issue by boovius** [pendo-io/RN-demo-app-React-Navigation#1]
Hi there :) 

Thanks for this tutorial. It seems really helpful and helped me understand some things that weren't so clear in the pendo docs. I've followed the steps outlined in this tutorial all to a "T" and my app is getting launched. 

I'm seeing the xcode build logs say `Pendo Mobile SDK was successfully integrated and connected to the server.` 

But then getting the following JS error: 

```
 ERROR  TypeError: Cannot call a class as a function, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
``` 

using: 
* react-native 0.63
* react-navigation/core 5.15.1
* pendo SDK 2.15.2

Would dearly appreciate some help. Thank you

**Comment by MikePendo** [comment]
I am not sure why this issue was closed with any resolution ....
@boovius if the question is still relevant please let us know and I will reopen it
in any case we r answering then question in the official SDK GitHub repo [here](https://github.com/pendo-io/pendo-mobile-ios/blob/master/pnddocs/react_native.md)
