### ISSUE TITLE
Getting screen container tag not found warning.

### ISSUE THREAD

**Issue by gozegotushar** [pendo-io/RN-demo-app-React-Navigation#11]
Hi team we are getting **screen container tag not found** warning, How can we resolve it ?
we are using : rn-pendo-sdk@^2.22.0:

```
 DEBUG  [rn-pendo-sdk]  Bottom Tab Bar discovered  1217
 DEBUG  [rn-pendo-sdk]  No rootTags were found, will use screenContainer tag
 WARN  [rn-pendo-sdk]  analyze (simple flow) screenId:BottomTabBar. Original error: findScreenContainerRootTag - screen container tag not found
```

**Comment by MikePendo** [comment]
@gozegotushar I only noticed your issue now, we dont answer tickets on those repos please submit your ticket in our official Pendo repo here: [Pendo GitHub](https://github.com/pendo-io/pendo-mobile-sdk) with all the relevant info

**Comment by MikePendo** [comment]
I would also recommend to use the latest version
