### ISSUE TITLE
App with Pendo RN implementation 

### ISSUE THREAD

**Issue by shariq-muhammad** [pendo-io/RN-demo-app-React-Navigation#2]
In our React Native app, we have implemented Pendo with TypeScript. We are having issues with iOS where it is throwing error that states: 
["State must not be null. 
 any analytics on this screen would be ignored 
 please refer to new installation instruction "]

Stacktrace is attached: 

<img width="437" alt="Screen Shot 2022-10-02 at 7 04 22 PM" src="https://user-images.githubusercontent.com/114886432/193480528-7a5114fe-8eac-483c-8add-ef6a2c3de975.png">

**Comment by MikePendo** [comment]
@shariq-muhammad 
It means the integration wasn't successful, i.e u dont pass the state on the `stateChange` prop OR u pass it as nil.
1. Please make sure you r following the [docs](https://github.com/pendo-io/pendo-mobile-ios/blob/master/pnddocs/react_native.md) (and try to submit the ticket there)
2. Can you please share the snippets of your code integration especially the one you wrap your `NavigationContainer`

**Comment by shariq-muhammad** [comment]
@MikePendo Is there a place where I can send you the snippets?

**Comment by MikePendo** [comment]
@shariq-muhammad 
sure ,u can send it right here

**Comment by MikePendo** [comment]
@shariq-muhammad 
Is the issue still relevant

**Comment by shariq-muhammad** [comment]
@MikePendo This can be closed for now. If needed, I'll create another.
