### ISSUE TITLE
React Native App with React Navigation in TypeScript - Build for iOS is failing

### ISSUE THREAD

**Issue by shariq-muhammad** [pendo-io/RN-demo-app-React-Navigation#4]
When building the React Native app, it failed for iOS with many errors for Pendo.arm64.xar:

Clang: cd /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temptc3472sy
     ['/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', '-cc1', '-cc1', '-triple', 'arm64-apple-ios9.0.0', '-emit-obj', '--mrelax-relocations', '-disable-llvm-passes', '-faligned-alloc-unavailable', '-target-sdk-version=15.4', '-fvisibility-inlines-hidden-static-local-var', '-target-abi', 'darwinpcs', '-Os', '-x', 'ir', '002', '-o', '002.o']
    -= Output =-
    Cannot take the address of an intrinsic!
      %18 = tail call i8* bitcast (i8* (i8*, i8*, ...)* @objc_msgSend to i8* (i8*, i8*)*)(i8* %16, i8* %17) #12 [ "clang.arc.attachedcall"(i8* (i8*)* @llvm.objc.retainAutoreleasedReturnValue) ], !dbg !53, !clang.arc.no_objc_arc_exceptions !41
    Cannot take the address of an intrinsic!
...
...
...
...
...
...
...

     %37 = call %7* bitcast (i8* (i8*, i8*, ...)* @objc_msgSend to %7* (i8*, i8*)*)(i8* %35, i8* %36) #7 [ "clang.arc.attachedcall"(i8* (i8*)* @llvm.objc.retainAutoreleasedReturnValue) ], !dbg !603
    fatal error: error in backend: Broken module found, compilation aborted!
    Exited with 70
   
    Failed to compile bundle: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Pendonzdrrlvp/Pendo.arm64.xar
 
Stderr:
 
> 
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:372:in `run'
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:2886:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:2825:in `each'
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:2825:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:3112:in `block in ProcessIPA'
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:3073:in `each'
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:3073:in `ProcessIPA'
    /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:4035:in `<main>'}
 
** EXPORT FAILED **
 
##[error]Error: /usr/bin/xcodebuild failed with return code: 70

**Comment by MikePendo** [comment]
@shariq-muhammad 
I will soon look in to the issue please next time submit the ticket to our iOS SDK plugin: 
[Pendo iOS SDK](https://github.com/pendo-io/RN-demo-app-React-Navigation/pulse)

**Comment by MikePendo** [comment]
@shariq-muhammad 
I must admit I never seen such errors before. I have tried to run it on my side and I didnt see any issues.
The Only difference that I see is that I currently  I use _Xcode 13.4_
(I would recommend  to use the latest Xcode 13, as Xcode 14 official was released couple of days ago)
Have u made any changes to the package json OR Podfile? like updating versions? 
Do u build for Simulator OR Device ?
Do you build it via terminal or Xcode (I think u try to Archive it )? if from terminal please share the exact command 
Please go to iOS folder and do the following (lets try to set the pods from the scratch)
`pod deintegrate ` 
`pod install`
In the XCode please clean the project and try to build/run again
I would like you to build it via Xcode and send me the error output.
After you build in Xcode press `CMD+ 9` that will open all your builds select the build on left pane and in the upper bar u will see and `Error Only` segment I would like to see that full output from there (please expand it if necessary)
<img width="1132" alt="Screen Shot 2022-10-06 at 11 01 02" src="https://user-images.githubusercontent.com/56674958/194347938-79556869-bd63-4bbc-bb13-5a6b161306d7.png">

**Comment by MikePendo** [comment]
I am also not sure is the posted issue is related to that specific app OR the error is from a different app?

**Comment by shariq-muhammad** [comment]
Error is from our App built on React-Native using React Navigation and TypeScript. App seem to be integrated with Pendo as when I run it locally in an emulator I can see the Pendo integration success message in Xcode and I can see visitor/account data in Pendo's people/vistor page. I can build my app locally. However, when CI/CD tries to build it at Microsoft AppCenter it fails with the error as above. 
I was told by Pendo support staff that I should create ticket on GitHub, so that is why I raised the issue here. Please point me to a better channel if this is not the right place for this.

**Comment by MikePendo** [comment]
@shariq-muhammad 
In that case please open a new issue [here](https://github.com/pendo-io/pendo-mobile-ios) with the link of that thread 
With all the information included, as your question not really related to current repo (For instance I had no idea that the issue was in AppCenter )
Maybe it will be a good idea to also ask Appcenter about that. As u mentioned u have no issue in building/runing it locally so there might be something different in the Appcenter config. 
For Instance are all the configs identical, like Xcode ?
What exactly u try to do in App Canter? u try to upload it to AppStore u try to archive it (I didnt really work with AppCenter, I can try to use this app and upload it to Appcenter and see how it goes)

**Comment by MikePendo** [comment]
I am closing this thread as its simply not related to that specific repo (if u dont mind)

**Comment by shariq-muhammad** [comment]
@MikePendo 
ok. I opened the issue [here.](https://github.com/pendo-io/pendo-mobile-ios/issues/18#issue-1400015269)
