### ISSUE TITLE
export default withPendoRN(App) requires a second parameter

### ISSUE THREAD

**Issue by trajano** [pendo-io/RN-demo-app-React-Navigation#7]
According to the types it is 

```
export function withPendoRN<P, C = React.JSXElementConstructor<P>>(NavigationContainer: C, options: RNTraverseOptions | null): any;
```

The `options` is not optional according to the types so it should say

```
export default withPendoRN(App, null) ;
```

or the typing needs to change.

**Comment by MikePendo** [comment]
I am sorry we usually don't track issues in that repo please open an issue on the official sdk github [here](https://github.com/pendo-io/pendo-mobile-ios/tree/swiftui)
We have changed our integration with a much simpler form that include only one line of code [here](https://github.com/pendo-io/pendo-mobile-ios/blob/master/pnddocs/react_native.md)
