### ISSUE TITLE
Pendo with react navigation 3

### ISSUE THREAD

**Issue by iAtharZaib** [pendo-io/RN-demo-app-React-Navigation#8]
Hi, I am integrating Pendo SDK on android with react-navigation 3 but it fails to verify hence not verifying the integration neither the tracks logging on the dashboard. Is there any way I can do the needful? 

Working fine with the same on iOS but android is creating issues.  [React Native version 0.62.2]

Thanks in Advance.

**Comment by MikePendo** [comment]
I am sorry we usually don't track issues in that repo please open an issue on the official sdk github [here](https://github.com/pendo-io/pendo-mobile-ios/tree/swiftui)
Usually this type of issue happens coz of bad integration, please make sure u r calling setup and start session as early as possible 
We have changed our integration with a much simpler form that include only one line of code [here](https://github.com/pendo-io/pendo-mobile-ios/blob/master/pnddocs/react_native.md)
